# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ynetaddr}
  s.version = "1.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniele Orlandi"]
  s.date = %q{2011-01-31}
  s.description = %q{Implements MAC address, IPv4/IPv6 addresses/networks/interfaces}
  s.email = %q{daniele@orlandi.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "VERSION",
    "lib/net/ip_addr.rb",
    "lib/net/ip_if_addr.rb",
    "lib/net/ip_net.rb",
    "lib/net/ip_tree.rb",
    "lib/net/ipv4_addr.rb",
    "lib/net/ipv4_if_addr.rb",
    "lib/net/ipv4_net.rb",
    "lib/net/ipv6_addr.rb",
    "lib/net/ipv6_if_addr.rb",
    "lib/net/ipv6_net.rb",
    "lib/net/mac_addr.rb",
    "lib/ynetaddr.rb",
    "spec/ip_net_spec.rb",
    "spec/ip_tree_spec.rb",
    "spec/ipv4_addr_spec.rb",
    "spec/ipv4_if_addr_spec.rb",
    "spec/ipv4_net_spec.rb",
    "spec/ipv6_addr_spec.rb",
    "spec/ipv6_if_addr_spec.rb",
    "spec/ipv6_net_spec.rb",
    "spec/mac_addr_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://www.orlandi.com/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Network addressing object}
  s.test_files = [
    "spec/ip_net_spec.rb",
    "spec/ip_tree_spec.rb",
    "spec/ipv4_addr_spec.rb",
    "spec/ipv4_if_addr_spec.rb",
    "spec/ipv4_net_spec.rb",
    "spec/ipv6_addr_spec.rb",
    "spec/ipv6_if_addr_spec.rb",
    "spec/ipv6_net_spec.rb",
    "spec/mac_addr_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

